### ISSUE TITLE
[bug] Error en git clone

### ISSUE THREAD

**Issue by nicmartinez** [ING559/Syllabus-2021-2#1]
Al intentar clonar el repo en windows ocurre el siguiente error

![image](https://user-images.githubusercontent.com/41973090/141840755-c6a8502b-c5b2-4c0e-be05-19b450512925.png)

**Comment by alanezz** [comment]
Hola,

Es porque se me coló un ícono de Google Drive en la carpeta. Ahora debería estar bien.

Saludos!

**Comment by nicmartinez** [comment]
gracias profe!
